# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1epzGhjLx0eAm1588tQ6hVObFQtaXBh8D
"""

!git clone https://github.com/tensorflow/examples.git

import sys
sys.path.append('/content/examples')
from tensorflow_examples.models.pix2pix import pix2pix

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

def load_image_pair():
    input_image = tf.random.uniform([256, 256, 3])
    target_image = tf.random.uniform([256, 256, 3])
    return input_image, target_image

dataset = tf.data.Dataset.from_tensor_slices([0]*10)
dataset = dataset.map(lambda x: load_image_pair())
dataset = dataset.batch(1)

generator = pix2pix.unet_generator(output_channels=3)
discriminator = pix2pix.discriminator(target=True)

print("Generator and Discriminator created successfully ✅")

for input_image, target_image in dataset.take(1):
    prediction = generator(input_image, training=False)

plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.title("Input Image")
plt.imshow(input_image[0])
plt.axis("off")

plt.subplot(1,3,2)
plt.title("Generated Image")
plt.imshow(prediction[0])
plt.axis("off")

plt.subplot(1,3,3)
plt.title("Target Image")
plt.imshow(target_image[0])
plt.axis("off")

plt.show()

def denormalize(image):
    return (image + 1) / 2

plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.title("Input Image")
plt.imshow(input_image[0])
plt.axis("off")

plt.subplot(1,3,2)
plt.title("Generated Image")
plt.imshow(denormalize(prediction[0]))
plt.axis("off")

plt.subplot(1,3,3)
plt.title("Target Image")
plt.imshow(target_image[0])
plt.axis("off")

plt.show()